### PR TITLE
UI layout for Currency Converter App

### PR DESCRIPTION
**Pull request by harlyon**
**What does this PR do?**
UI layout for Currency Converter Application

**Description of Task to be completed?**
A single 1-columned layout page with a search input field

**How should this be manually tested?**
1. git clone https://github.com/DevXonnect/Xonnect-Currency-Converter
2. cd Xonnect-Currency-Converter
3. npm install
4. npm start
5. The application should be run on the browser on port 3000

**Screenshots**
selection_071

### CODE REVIEW

**Comment by albert85** [comment]
@harlyon Please Description title does not follow the workflow and other headings. Please check an example in the attached link. Please click [here](https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices)

**Comment by albert85** [comment]
Please also check your commit message using the workflow I shared the link on the previous comment, and please you are not merging to master, try changing your compare with `Currency-Converter` branch
Use this template below for your commit message
screen shot 2018-12-14 at 12 50 32 pm

**Comment by harlyon** [comment]
@albert85 check
@harlyon remove the hyphen in the title. Also try to make the title a sentence case
@harlyon under `How should this be manually tested?`, try to list step by step will be needed to be able to test this PR. e.g. 1. Clone this repo using `git clone github//dfodjdogdjodjgjodo.git`

**Comment by harlyon** [comment]
@albert85 
@harlyon You don't need to include ft on the PR title

**Comment by harlyon** [comment]
@albert85 
@harlyon itemize the steps on `How should this be manually tested?`

**Pull request merged**
